import { useMemo, useState } from 'react'
import type { ScriptId } from '@/types'
import { Button } from '../components/Button'
import { RoleIcon } from '../components/RoleIcon'
import { Screen } from '../components/Screen'

type TrainingCase = { id: string; script: ScriptId; roleId: string; title: string; situation: string; expected: string }

const CASES: TrainingCase[] = [
  { id: 'tb-monk', script: 'trouble-brewing', roleId: 'monk', title: 'Moine contre Démon', situation: 'Le Moine protège Alice, puis le Diablotin cible Alice.', expected: 'Alice reste vivante ; le grimoire doit signaler que la protection a empêché la mort.' },
  { id: 'tb-undertaker', script: 'trouble-brewing', roleId: 'undertaker', title: 'Croque-mort', situation: 'Bruno est exécuté avec le rôle Baron.', expected: 'La nuit suivante, le Croque-mort peut voir « Baron » directement sur la tablette.' },
  { id: 'bmr-innkeeper', script: 'bad-moon-rising', roleId: 'innkeeper', title: 'Aubergiste', situation: 'Alice et Benoît sont choisis ; Benoît devient ivre.', expected: 'Les deux survivent à la nuit. Benoît est ivre jusqu’au crépuscule suivant, pas seulement jusqu’à l’aube.' },
  { id: 'bmr-pukka', script: 'bad-moon-rising', roleId: 'pukka', title: 'Pukka', situation: 'Chloé a été empoisonnée la nuit dernière.', expected: 'Chloé meurt puis redevient saine ; une nouvelle cible est empoisonnée. Vérifier aussi le cas Pukka ivre.' },
  { id: 'bmr-godfather', script: 'bad-moon-rising', roleId: 'godfather', title: 'Parrain', situation: 'Un Paria est exécuté et meurt réellement.', expected: 'La nuit suivante seulement, le Parrain reçoit son choix de meurtre.' },
  { id: 'bmr-zombuul', script: 'bad-moon-rising', roleId: 'zombuul', title: 'Zombuul', situation: 'Le Zombuul devrait mourir pour la première fois.', expected: 'Il paraît mort publiquement mais reste réellement vivant : vérifier l’annonce, le grimoire et les interactions.' },
]

type Quiz = { id: string; script: ScriptId; roleId: string; question: string; options: string[]; answer: number; explanation: string }
const QUIZZES: Quiz[] = [
  { id: 'tb-monk', script: 'trouble-brewing', roleId: 'monk', question: 'Le Moine protège Alice et le Diablotin la cible. Que se passe-t-il ?', options: ['Alice meurt.', 'Alice survit.', 'Le Moine meurt.'], answer: 1, explanation: 'La protection du Moine bloque une mort causée par le Démon cette nuit.' },
  { id: 'tb-undertaker', script: 'trouble-brewing', roleId: 'undertaker', question: 'Que voit le Croque-mort après une exécution ?', options: ['Le rôle réel de la personne exécutée.', 'Son alignement seulement.', 'Le grimoire entier.'], answer: 0, explanation: 'Le Croque-mort apprend le personnage réel du joueur exécuté la veille.' },
  { id: 'bmr-innkeeper', script: 'bad-moon-rising', roleId: 'innkeeper', question: 'Combien de temps dure l’ivresse décidée par l’Aubergiste ?', options: ['Jusqu’à l’aube.', 'Jusqu’au crépuscule suivant.', 'Toute la partie.'], answer: 1, explanation: 'La cible est ivre pendant la nuit et le jour suivant, jusqu’au crépuscule.' },
  { id: 'bmr-godfather', script: 'bad-moon-rising', roleId: 'godfather', question: 'Quand le Parrain obtient-il son meurtre ?', options: ['Après la mort nocturne d’un Paria.', 'Après la mort diurne effective d’un Paria.', 'Chaque nuit.'], answer: 1, explanation: 'Un Paria doit réellement mourir pendant la journée ; le Parrain agit la nuit suivante.' },
  { id: 'bmr-zombuul', script: 'bad-moon-rising', roleId: 'zombuul', question: 'Lors de sa première mort, que devient le Zombuul ?', options: ['Il meurt réellement.', 'Il paraît mort mais reste en vie.', 'Il revient le lendemain.'], answer: 1, explanation: 'Sa première mort est publique, mais le Zombuul demeure réellement vivant.' },
  { id: 'tb-washerwoman', script: 'trouble-brewing', roleId: 'washerwoman', question: 'Que montre la Lavandière ?', options: ['Deux joueurs dont l’un est un Villageois précis.', 'Un joueur méchant.', 'Deux rôles de Sbires.'], answer: 0, explanation: 'La Lavandière apprend deux joueurs, dont l’un possède le Villageois montré.' },
  { id: 'tb-librarian', script: 'trouble-brewing', roleId: 'librarian', question: 'Que se passe-t-il s’il n’y a aucun Paria en jeu ?', options: ['La Libraire apprend « aucun Paria ».', 'Elle reçoit deux faux noms.', 'Elle devient ivre.'], answer: 0, explanation: 'La Libraire est informée qu’aucun Paria n’est en jeu.' },
  { id: 'tb-investigator', script: 'trouble-brewing', roleId: 'investigator', question: 'Quel type de rôle l’Enquêteur recherche-t-il ?', options: ['Un Démon.', 'Un Sbire.', 'Un Paria.'], answer: 1, explanation: 'Il voit deux joueurs, dont l’un est le Sbire indiqué.' },
  { id: 'tb-chef', script: 'trouble-brewing', roleId: 'chef', question: 'Que compte le Chef ?', options: ['Les joueurs morts.', 'Les paires de joueurs méchants voisins.', 'Les rôles de Villageois.'], answer: 1, explanation: 'Le Chef apprend le nombre de paires de voisins tous deux méchants.' },
  { id: 'tb-empath', script: 'trouble-brewing', roleId: 'empath', question: 'Que compte l’Empathique ?', options: ['Ses voisins vivants méchants.', 'Tous les joueurs méchants.', 'Les joueurs empoisonnés.'], answer: 0, explanation: 'Seuls ses voisins vivants et méchants comptent.' },
  { id: 'tb-ravenkeeper', script: 'trouble-brewing', roleId: 'ravenkeeper', question: 'Quand le Gardien se réveille-t-il ?', options: ['Chaque nuit.', 'Uniquement s’il meurt la nuit.', 'Après chaque exécution.'], answer: 1, explanation: 'S’il meurt la nuit, il choisit un joueur et apprend son rôle.' },
  { id: 'tb-soldier', script: 'trouble-brewing', roleId: 'soldier', question: 'Le Soldat peut-il mourir à cause du Démon ?', options: ['Oui, toujours.', 'Non, tant qu’il est sobre.', 'Seulement par exécution.'], answer: 1, explanation: 'Le Démon ne peut pas tuer le Soldat sobre.' },
  { id: 'tb-virgin', script: 'trouble-brewing', roleId: 'virgin', question: 'Quel événement peut déclencher la Vierge ?', options: ['La première nomination par un Villageois.', 'Toute mort nocturne.', 'Un vote fantôme.'], answer: 0, explanation: 'La première fois qu’un Villageois la nomme, il peut être exécuté immédiatement.' },
  { id: 'tb-slayer', script: 'trouble-brewing', roleId: 'slayer', question: 'Que doit viser le Mercenaire pour gagner ?', options: ['Le Démon.', 'Un Sbire.', 'Un Paria.'], answer: 0, explanation: 'Une fois par partie, il désigne un joueur : s’il s’agit du Démon, le Bien gagne.' },
  { id: 'tb-mayor', script: 'trouble-brewing', roleId: 'mayor', question: 'Si trois joueurs sont vivants et personne n’est exécuté, que peut provoquer le Maire ?', options: ['Victoire du Bien.', 'Victoire du Mal.', 'Une nuit supplémentaire.'], answer: 0, explanation: 'Le Maire peut faire gagner le Bien dans cette situation.' },
  { id: 'tb-butler', script: 'trouble-brewing', roleId: 'butler', question: 'Avec qui le Majordome doit-il voter ?', options: ['Son maître.', 'Le Démon.', 'N’importe quel mort.'], answer: 0, explanation: 'Il ne peut voter que si son maître vote aussi.' },
  { id: 'tb-drunk', script: 'trouble-brewing', roleId: 'drunk', question: 'Que croit être l’Ivrogne ?', options: ['Un Villageois absent.', 'Un Sbire.', 'Son vrai rôle de Paria.'], answer: 0, explanation: 'Il croit avoir un rôle de Villageois absent, mais son pouvoir ne fonctionne pas.' },
  { id: 'tb-recluse', script: 'trouble-brewing', roleId: 'recluse', question: 'Comment le Reclus peut-il être perçu ?', options: ['Comme méchant ou Démon.', 'Toujours comme gentil.', 'Comme mort uniquement.'], answer: 0, explanation: 'Le Conteur peut le faire enregistrer comme méchant, Sbire ou Démon.' },
  { id: 'tb-saint', script: 'trouble-brewing', roleId: 'saint', question: 'Que déclenche l’exécution du Saint ?', options: ['Victoire immédiate du Mal.', 'Victoire du Bien.', 'Rien de spécial.'], answer: 0, explanation: 'Si le Saint est exécuté, le Mal gagne immédiatement.' },
  { id: 'tb-poisoner', script: 'trouble-brewing', roleId: 'poisoner', question: 'Combien de joueurs l’Empoisonneur cible-t-il chaque nuit ?', options: ['Un.', 'Deux.', 'Aucun : il est passif.'], answer: 0, explanation: 'Il choisit un joueur vivant, empoisonné jusqu’à l’aube suivante.' },
  { id: 'tb-baron', script: 'trouble-brewing', roleId: 'baron', question: 'Quel effet de mise en place a le Baron ?', options: ['+2 Parias, -2 Villageois.', '+1 Sbire.', '+1 Démon.'], answer: 0, explanation: 'Le Baron modifie la composition avec deux Parias supplémentaires.' },
  { id: 'tb-scarlet', script: 'trouble-brewing', roleId: 'scarlet-woman', question: 'Quand la Confidente devient-elle Démon ?', options: ['Quand le Démon meurt avec au moins cinq joueurs vivants.', 'À chaque nuit.', 'Quand un Sbire est exécuté.'], answer: 0, explanation: 'Elle reprend le rôle du Démon si les conditions de vivants sont réunies.' },
  { id: 'bmr-sailor', script: 'bad-moon-rising', roleId: 'sailor', question: 'Qui le Marin peut-il choisir ?', options: ['Un vivant, lui-même inclus.', 'Seulement un autre Villageois.', 'Uniquement un mort.'], answer: 0, explanation: 'Le Marin peut se choisir ; lui ou sa cible devient alors ivre.' },
  { id: 'bmr-chambermaid', script: 'bad-moon-rising', roleId: 'chambermaid', question: 'Que montre la Concierge ?', options: ['Combien de ses deux cibles se sont réveillées grâce à leur pouvoir.', 'Leur alignement.', 'Le rôle des deux cibles.'], answer: 0, explanation: 'Les joueurs ivres ou empoisonnés comptent s’ils se sont réveillés à cause de leur pouvoir.' },
  { id: 'bmr-exorcist', script: 'bad-moon-rising', roleId: 'exorcist', question: 'Que se passe-t-il si l’Exorciste cible le Démon ?', options: ['Le Démon ne fait pas son action et apprend qui est l’Exorciste.', 'Le Démon meurt.', 'L’Exorciste devient ivre.'], answer: 0, explanation: 'Le Démon est empêché d’utiliser son pouvoir cette nuit.' },
  { id: 'bmr-gambler', script: 'bad-moon-rising', roleId: 'gambler', question: 'Le Parieur apprend-il si son annonce est correcte ?', options: ['Oui.', 'Non.', 'Seulement s’il est méchant.'], answer: 1, explanation: 'S’il se trompe il meurt ; sinon il ne reçoit aucune confirmation.' },
  { id: 'bmr-courtier', script: 'bad-moon-rising', roleId: 'courtier', question: 'Le Courtisan apprend-il si le rôle choisi est en jeu ?', options: ['Oui.', 'Non.', 'Seulement si c’est un Démon.'], answer: 1, explanation: 'Le pouvoir est dépensé ; le MJ rend le détenteur ivre s’il existe.' },
  { id: 'bmr-professor', script: 'bad-moon-rising', roleId: 'professor', question: 'Quel mort le Professeur peut-il réellement ressusciter ?', options: ['Un Villageois.', 'N’importe quel rôle.', 'Uniquement un Paria.'], answer: 0, explanation: 'Cibler un autre rôle consomme son pouvoir sans le ressusciter.' },
  { id: 'bmr-minstrel', script: 'bad-moon-rising', roleId: 'minstrel', question: 'Après l’exécution effective d’un Sbire, qui est ivre ?', options: ['Tous les autres joueurs.', 'Seulement les Villageois.', 'Le Démon uniquement.'], answer: 0, explanation: 'Tous les autres joueurs sont ivres cette nuit et le jour suivant.' },
  { id: 'bmr-tealady', script: 'bad-moon-rising', roleId: 'tea-lady', question: 'Quand les voisins de l’Herboriste sont-ils protégés ?', options: ['Quand ils sont tous deux gentils.', 'Quand ils sont morts.', 'Uniquement pendant le jour.'], answer: 0, explanation: 'Ses deux voisins vivants les plus proches doivent être gentils.' },
  { id: 'bmr-pacifist', script: 'bad-moon-rising', roleId: 'pacifist', question: 'Le Pacifiste sauve-t-il automatiquement un gentil exécuté ?', options: ['Oui.', 'Non, le MJ décide.', 'Seulement le premier jour.'], answer: 1, explanation: 'Le pouvoir dit « peut survivre » : le Conteur choisit le résultat.' },
  { id: 'bmr-fool', script: 'bad-moon-rising', roleId: 'fool', question: 'Combien de fois le Bouffon survit-il à une mort ?', options: ['La première fois seulement.', 'Deux fois.', 'À chaque fois.'], answer: 0, explanation: 'Il consomme sa protection à la première mort qui devrait le tuer.' },
  { id: 'bmr-goon', script: 'bad-moon-rising', roleId: 'goon', question: 'Que devient le premier joueur qui cible le Bras droit ?', options: ['Ivre jusqu’au crépuscule.', 'Mort.', 'Protégé.'], answer: 0, explanation: 'Le Bras droit adopte aussi l’alignement de ce joueur.' },
  { id: 'bmr-lunatic', script: 'bad-moon-rising', roleId: 'lunatic', question: 'Que sait le vrai Démon au sujet du Lunatique ?', options: ['Son identité et ses cibles.', 'Son rôle seulement.', 'Rien.'], answer: 0, explanation: 'Le Lunatique croit être Démon, tandis que le vrai Démon suit ses choix.' },
  { id: 'bmr-moonchild', script: 'bad-moon-rising', roleId: 'moonchild', question: 'Quand la cible du Moonchild meurt-elle ?', options: ['La nuit suivante, si elle était gentille au choix.', 'Immédiatement, quelle que soit son équipe.', 'Au prochain jour.'], answer: 0, explanation: 'L’alignement à retenir est celui au moment où le Moonchild désigne sa cible.' },
  { id: 'bmr-assassin', script: 'bad-moon-rising', roleId: 'assassin', question: 'Que traverse la mort de l’Assassin ?', options: ['Toutes les protections.', 'Seulement les protections de nuit.', 'Aucune protection.'], answer: 0, explanation: 'L’Assassin tue même si la victime devrait survivre.' },
  { id: 'bmr-mastermind', script: 'bad-moon-rising', roleId: 'mastermind', question: 'Que déclenche le Cerveau après l’exécution du Démon ?', options: ['Une nuit et un dernier jour.', 'La victoire immédiate du Bien.', 'Deux jours supplémentaires.'], answer: 0, explanation: 'Le dernier jour tranche selon l’équipe de l’exécuté, ou l’absence d’exécution.' },
  { id: 'bmr-shabaloth', script: 'bad-moon-rising', roleId: 'shabaloth', question: 'Que peut faire le Shabaloth avant de choisir ses deux victimes ?', options: ['Régurgiter une victime précédente.', 'Ressusciter n’importe quel joueur.', 'Empoisonner un joueur.'], answer: 0, explanation: 'Il peut ramener une victime de sa précédente attaque, même si elle avait survécu.' },
  { id: 'bmr-po', script: 'bad-moon-rising', roleId: 'po', question: 'Après avoir choisi personne, que doit faire Po la nuit suivante ?', options: ['Choisir trois joueurs.', 'Rester inactif.', 'Tuer le Parrain.'], answer: 0, explanation: 'Po doit choisir exactement trois joueurs la nuit suivante.' },
]

export function TrainingScreen({ onBack }: { onBack: () => void }) {
  const [script, setScript] = useState<ScriptId>('trouble-brewing')
  const [mode, setMode] = useState<'test' | 'learn'>('test')
  const [index, setIndex] = useState(0)
  const [showReport, setShowReport] = useState(false)
  const [report, setReport] = useState('')
  const [quizIndex, setQuizIndex] = useState(0)
  const [quizAnswer, setQuizAnswer] = useState<number | null>(null)
  const [quizScore, setQuizScore] = useState(0)
  const cases = useMemo(() => CASES.filter((item) => item.script === script), [script])
  const quizPool = useMemo(() => QUIZZES.filter((item) => item.script === script), [script])
  const [quizSession, setQuizSession] = useState<Quiz[]>([])
  const current = cases[index]!
  const reportText = `Cas entraînement : ${current.title}\nScénario : ${script}\nSituation : ${current.situation}\nAttendu : ${current.expected}\nObservé : ${report || '(à compléter)'}`

  if (mode === 'learn') {
    const quiz = quizSession[quizIndex]
    if (!quiz) return <Screen title="Parcours terminé" subtitle={`${quizScore} / 5 bonnes réponses`} onBack={onBack}><div className="max-w-xl mx-auto text-center flex flex-col gap-5"><p className="text-5xl font-bold text-accent">{quizScore} / 5</p><p className="text-ink-2">{quizScore === 5 ? 'Excellent : tu maîtrises ces fondamentaux.' : 'Relance le parcours : cinq nouvelles questions seront tirées au sort.'}</p><Button variant="primary" onClick={() => { setQuizSession([...quizPool].sort(() => Math.random() - 0.5).slice(0, 5)); setQuizIndex(0); setQuizScore(0); setQuizAnswer(null) }}>Nouveau test aléatoire</Button></div></Screen>
    return <Screen title={`Parcours Conteur — ${quizIndex + 1} / 5`} subtitle="5 questions tirées aléatoirement dans la banque du scénario." onBack={onBack}><div className="max-w-2xl mx-auto flex flex-col gap-5"><section className="bg-surface-1 border border-accent/35 rounded-2xl p-6"><div className="flex items-center gap-3"><RoleIcon characterId={quiz.roleId} size={48} /><div><p className="text-xs uppercase tracking-wide text-accent">Question de règle</p><h2 className="text-xl font-semibold">À toi de décider</h2></div></div><p className="mt-5 text-lg">{quiz.question}</p></section><div className="grid gap-2">{quiz.options.map((option, optionIndex) => <button key={option} disabled={quizAnswer !== null} onClick={() => setQuizAnswer(optionIndex)} className={`text-left rounded-xl border px-4 py-4 ${quizAnswer !== null && optionIndex === quiz.answer ? 'border-success bg-success/10' : quizAnswer === optionIndex ? 'border-danger bg-danger/10' : 'border-border bg-surface-1 hover:border-accent'}`}>{option}</button>)}</div>{quizAnswer !== null && <section className={`rounded-xl border p-4 ${quizAnswer === quiz.answer ? 'border-success bg-success/10' : 'border-warn/40 bg-warn/10'}`}><p className="font-semibold">{quizAnswer === quiz.answer ? 'Bonne réponse' : 'À retenir'}</p><p className="text-sm mt-1">{quiz.explanation}</p><Button variant="primary" className="mt-4" onClick={() => { if (quizAnswer === quiz.answer) setQuizScore((value) => value + 1); setQuizIndex((value) => value + 1); setQuizAnswer(null) }}>Suivant</Button></section>}</div></Screen>
  }

  return <Screen title="Mode entraînement du Conteur" subtitle="Teste le moteur ou entraîne tes connaissances de MJ." onBack={onBack}>
    <div className="max-w-2xl mx-auto flex flex-col gap-5">
      <div className="grid grid-cols-2 gap-2"><Button variant="primary">Tester l’application</Button><Button variant="secondary" onClick={() => { setQuizSession([...quizPool].sort(() => Math.random() - 0.5).slice(0, 5)); setMode('learn'); setQuizIndex(0); setQuizScore(0); setQuizAnswer(null) }}>Test de connaissances · 5 questions</Button></div>
      <div className="grid grid-cols-2 gap-2">{(['trouble-brewing', 'bad-moon-rising'] as ScriptId[]).map((id) => <Button key={id} variant={script === id ? 'primary' : 'secondary'} onClick={() => { setScript(id); setIndex(0); setShowReport(false); setReport(''); setQuizIndex(0); setQuizScore(0); setQuizAnswer(null) }}>{id === 'trouble-brewing' ? 'Trouble Brewing' : 'Bad Moon Rising'}</Button>)}</div>
      <div className="flex gap-1" aria-label="Progression">{cases.map((item, itemIndex) => <div key={item.id} className={`h-1.5 flex-1 rounded-full ${itemIndex === index ? 'bg-accent' : itemIndex < index ? 'bg-success' : 'bg-surface-3'}`} />)}</div>
      <section className="bg-surface-1 border border-accent/35 rounded-2xl p-6"><div className="flex gap-3 items-center"><RoleIcon characterId={current.roleId} size={48} /><div><p className="text-xs uppercase tracking-wide text-accent">Cas de contrôle {index + 1} / {cases.length}</p><h2 className="text-xl font-semibold">{current.title}</h2></div></div><p className="mt-5 leading-relaxed">{current.situation}</p><div className="mt-5 border-l-2 border-success pl-4"><p className="text-xs uppercase tracking-wide text-success">Résultat attendu</p><p className="text-sm text-ink-1 mt-1">{current.expected}</p></div></section>
      <section className="bg-warn/10 border border-warn/35 rounded-xl p-4"><p className="font-medium">Tester dans une vraie partie bac à sable</p><p className="text-sm text-ink-2 mt-1">Lance le scénario correspondant, reproduis cette situation avec le grimoire et compare le comportement observé au résultat attendu.</p><div className="flex flex-wrap gap-2 mt-4"><Button variant="secondary" onClick={() => setShowReport((value) => !value)}>Signaler un écart</Button><Button variant="primary" onClick={() => { setIndex((value) => (value + 1) % cases.length); setShowReport(false); setReport('') }}>Cas suivant</Button></div></section>
      {showReport && <section className="bg-surface-1 border border-danger/40 rounded-xl p-4"><p className="font-medium">Rapport de reproduction</p><textarea value={report} onChange={(event) => setReport(event.target.value)} placeholder="Décris ce que l’app a réellement fait, les rôles impliqués et l’étape de nuit…" className="mt-3 w-full min-h-28 bg-surface-2 border border-border rounded-lg p-3 text-sm" /><pre className="mt-3 whitespace-pre-wrap text-xs text-ink-2 bg-surface-2 rounded-lg p-3">{reportText}</pre></section>}
    </div>
  </Screen>
}
